#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin_Android.Resource", IsApplication=true)]

namespace Xamarin_Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorAnimationTypes = global::Xamarin_Android.Resource.Attribute.busyIndicatorAnimationTypes;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorIsBusy = global::Xamarin_Android.Resource.Attribute.busyIndicatorIsBusy;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorSecondaryColor = global::Xamarin_Android.Resource.Attribute.busyIndicatorSecondaryColor;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorTextColor = global::Xamarin_Android.Resource.Attribute.busyIndicatorTextColor;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorTextSize = global::Xamarin_Android.Resource.Attribute.busyIndicatorTextSize;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorTitle = global::Xamarin_Android.Resource.Attribute.busyIndicatorTitle;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorTitlePlacement = global::Xamarin_Android.Resource.Attribute.busyIndicatorTitlePlacement;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorViewBoxHeight = global::Xamarin_Android.Resource.Attribute.busyIndicatorViewBoxHeight;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Attribute.busyIndicatorViewBoxWidth = global::Xamarin_Android.Resource.Attribute.busyIndicatorViewBoxWidth;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.ball = global::Xamarin_Android.Resource.Id.ball;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.battery = global::Xamarin_Android.Resource.Id.battery;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.bottom = global::Xamarin_Android.Resource.Id.bottom;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.box = global::Xamarin_Android.Resource.Id.box;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.cupertino = global::Xamarin_Android.Resource.Id.cupertino;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.doubleCircle = global::Xamarin_Android.Resource.Id.doubleCircle;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.ecg = global::Xamarin_Android.Resource.Id.ecg;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.gearBox = global::Xamarin_Android.Resource.Id.gearBox;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.globe = global::Xamarin_Android.Resource.Id.globe;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.horizontalPulsingBox = global::Xamarin_Android.Resource.Id.horizontalPulsingBox;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.movieTimer = global::Xamarin_Android.Resource.Id.movieTimer;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.none = global::Xamarin_Android.Resource.Id.none;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.print = global::Xamarin_Android.Resource.Id.print;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.rectangle = global::Xamarin_Android.Resource.Id.rectangle;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.rollingBall = global::Xamarin_Android.Resource.Id.rollingBall;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.singleCircle = global::Xamarin_Android.Resource.Id.singleCircle;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.slicedCircle = global::Xamarin_Android.Resource.Id.slicedCircle;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.top = global::Xamarin_Android.Resource.Id.top;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Id.zoomingTarget = global::Xamarin_Android.Resource.Id.zoomingTarget;
			global::Com.Syncfusion.Sfbusyindicator.Resource.String.library_name = global::Xamarin_Android.Resource.String.library_name;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorAnimationTypes = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorAnimationTypes;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorIsBusy = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorIsBusy;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorSecondaryColor = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorSecondaryColor;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorTextColor = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorTextColor;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorTextSize = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorTextSize;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorTitle = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorTitle;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorTitlePlacement = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorTitlePlacement;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorViewBoxHeight = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorViewBoxHeight;
			global::Com.Syncfusion.Sfbusyindicator.Resource.Styleable.SfBusyIndicator_busyIndicatorViewBoxWidth = global::Xamarin_Android.Resource.Styleable.SfBusyIndicator_busyIndicatorViewBoxWidth;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialAnimationDuration = global::Xamarin_Android.Resource.Attribute.radialAnimationDuration;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonBackText = global::Xamarin_Android.Resource.Attribute.radialCenterButtonBackText;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonBackTextColor = global::Xamarin_Android.Resource.Attribute.radialCenterButtonBackTextColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonBackTextSize = global::Xamarin_Android.Resource.Attribute.radialCenterButtonBackTextSize;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonBackground = global::Xamarin_Android.Resource.Attribute.radialCenterButtonBackground;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonBorderColor = global::Xamarin_Android.Resource.Attribute.radialCenterButtonBorderColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonBorderThickness = global::Xamarin_Android.Resource.Attribute.radialCenterButtonBorderThickness;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonPlacement = global::Xamarin_Android.Resource.Attribute.radialCenterButtonPlacement;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonRadius = global::Xamarin_Android.Resource.Attribute.radialCenterButtonRadius;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonText = global::Xamarin_Android.Resource.Attribute.radialCenterButtonText;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonTextColor = global::Xamarin_Android.Resource.Attribute.radialCenterButtonTextColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialCenterButtonTextSize = global::Xamarin_Android.Resource.Attribute.radialCenterButtonTextSize;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialEnableCenterButtonAnimation = global::Xamarin_Android.Resource.Attribute.radialEnableCenterButtonAnimation;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialEnableRotation = global::Xamarin_Android.Resource.Attribute.radialEnableRotation;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialIsDragEnabled = global::Xamarin_Android.Resource.Attribute.radialIsDragEnabled;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialIsOpen = global::Xamarin_Android.Resource.Attribute.radialIsOpen;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialLayoutType = global::Xamarin_Android.Resource.Attribute.radialLayoutType;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialOuterRimColor = global::Xamarin_Android.Resource.Attribute.radialOuterRimColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialOuterRimThickness = global::Xamarin_Android.Resource.Attribute.radialOuterRimThickness;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialRimActiveColor = global::Xamarin_Android.Resource.Attribute.radialRimActiveColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialRimColor = global::Xamarin_Android.Resource.Attribute.radialRimColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialRimRadius = global::Xamarin_Android.Resource.Attribute.radialRimRadius;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialSelectionColor = global::Xamarin_Android.Resource.Attribute.radialSelectionColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialSeparatorColor = global::Xamarin_Android.Resource.Attribute.radialSeparatorColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialSeparatorThickness = global::Xamarin_Android.Resource.Attribute.radialSeparatorThickness;
			global::Syncfusion.SfRadialMenu.Android.Resource.Attribute.radialVisibleSegmentsCount = global::Xamarin_Android.Resource.Attribute.radialVisibleSegmentsCount;
			global::Syncfusion.SfRadialMenu.Android.Resource.Id.Center = global::Xamarin_Android.Resource.Id.Center;
			global::Syncfusion.SfRadialMenu.Android.Resource.Id.Custom = global::Xamarin_Android.Resource.Id.Custom;
			global::Syncfusion.SfRadialMenu.Android.Resource.Id.Default = global::Xamarin_Android.Resource.Id.Default;
			global::Syncfusion.SfRadialMenu.Android.Resource.Id.TopLeft = global::Xamarin_Android.Resource.Id.TopLeft;
			global::Syncfusion.SfRadialMenu.Android.Resource.String.library_name = global::Xamarin_Android.Resource.String.library_name;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu = global::Xamarin_Android.Resource.Styleable.SfRadialMenu;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialAnimationDuration = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialAnimationDuration;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackText = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackText;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackTextColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackTextColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackTextSize = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackTextSize;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackground = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBackground;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBorderColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBorderColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBorderThickness = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonBorderThickness;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonPlacement = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonPlacement;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonRadius = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonRadius;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonText = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonText;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonTextColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonTextColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialCenterButtonTextSize = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialCenterButtonTextSize;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialEnableCenterButtonAnimation = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialEnableCenterButtonAnimation;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialEnableRotation = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialEnableRotation;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialIsDragEnabled = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialIsDragEnabled;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialIsOpen = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialIsOpen;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialLayoutType = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialLayoutType;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialOuterRimColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialOuterRimColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialOuterRimThickness = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialOuterRimThickness;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialRimActiveColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialRimActiveColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialRimColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialRimColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialRimRadius = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialRimRadius;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialSelectionColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialSelectionColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialSeparatorColor = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialSeparatorColor;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialSeparatorThickness = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialSeparatorThickness;
			global::Syncfusion.SfRadialMenu.Android.Resource.Styleable.SfRadialMenu_radialVisibleSegmentsCount = global::Xamarin_Android.Resource.Styleable.SfRadialMenu_radialVisibleSegmentsCount;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int busyIndicatorAnimationTypes = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int busyIndicatorIsBusy = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int busyIndicatorSecondaryColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int busyIndicatorTextColor = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int busyIndicatorTextSize = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int busyIndicatorTitle = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int busyIndicatorTitlePlacement = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int busyIndicatorViewBoxHeight = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int busyIndicatorViewBoxWidth = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int radialAnimationDuration = 2130771977;
			
			// aapt resource value: 0x7F01000D
			public const int radialCenterButtonBackground = 2130771981;
			
			// aapt resource value: 0x7F01000A
			public const int radialCenterButtonBackText = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int radialCenterButtonBackTextColor = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int radialCenterButtonBackTextSize = 2130771980;
			
			// aapt resource value: 0x7F01000E
			public const int radialCenterButtonBorderColor = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int radialCenterButtonBorderThickness = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int radialCenterButtonPlacement = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int radialCenterButtonRadius = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int radialCenterButtonText = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int radialCenterButtonTextColor = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int radialCenterButtonTextSize = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int radialEnableCenterButtonAnimation = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int radialEnableRotation = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int radialIsDragEnabled = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int radialIsOpen = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int radialLayoutType = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int radialOuterRimColor = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int radialOuterRimThickness = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int radialRimActiveColor = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int radialRimColor = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int radialRimRadius = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int radialSelectionColor = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int radialSeparatorColor = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int radialSeparatorThickness = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int radialVisibleSegmentsCount = 2130772002;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int facebook = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Font = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int gplus = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int instagram = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int linkedin = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int pinterest = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int Previous = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int twitter = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030005
			public const int ball = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int battery = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int bottom = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int box = 2130903048;
			
			// aapt resource value: 0x7F030000
			public const int Center = 2130903040;
			
			// aapt resource value: 0x7F030009
			public const int cupertino = 2130903049;
			
			// aapt resource value: 0x7F030001
			public const int Custom = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Default = 2130903042;
			
			// aapt resource value: 0x7F03000A
			public const int doubleCircle = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int ecg = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int gearBox = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int globe = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int horizontalPulsingBox = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int movieTimer = 2130903055;
			
			// aapt resource value: 0x7F030003
			public const int MyButton = 2130903043;
			
			// aapt resource value: 0x7F030010
			public const int none = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int print = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int rectangle = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int rollingBall = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int singleCircle = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int slicedCircle = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int top = 2130903062;
			
			// aapt resource value: 0x7F030004
			public const int TopLeft = 2130903044;
			
			// aapt resource value: 0x7F030017
			public const int zoomingTarget = 2130903063;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int library_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008 }
			public static int[] SfBusyIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int SfBusyIndicator_busyIndicatorAnimationTypes = 0;
			
			// aapt resource value: 1
			public const int SfBusyIndicator_busyIndicatorIsBusy = 1;
			
			// aapt resource value: 2
			public const int SfBusyIndicator_busyIndicatorSecondaryColor = 2;
			
			// aapt resource value: 3
			public const int SfBusyIndicator_busyIndicatorTextColor = 3;
			
			// aapt resource value: 4
			public const int SfBusyIndicator_busyIndicatorTextSize = 4;
			
			// aapt resource value: 5
			public const int SfBusyIndicator_busyIndicatorTitle = 5;
			
			// aapt resource value: 6
			public const int SfBusyIndicator_busyIndicatorTitlePlacement = 6;
			
			// aapt resource value: 7
			public const int SfBusyIndicator_busyIndicatorViewBoxHeight = 7;
			
			// aapt resource value: 8
			public const int SfBusyIndicator_busyIndicatorViewBoxWidth = 8;
			
			// aapt resource value: { 0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022 }
			public static int[] SfRadialMenu = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int SfRadialMenu_radialAnimationDuration = 0;
			
			// aapt resource value: 4
			public const int SfRadialMenu_radialCenterButtonBackground = 4;
			
			// aapt resource value: 1
			public const int SfRadialMenu_radialCenterButtonBackText = 1;
			
			// aapt resource value: 2
			public const int SfRadialMenu_radialCenterButtonBackTextColor = 2;
			
			// aapt resource value: 3
			public const int SfRadialMenu_radialCenterButtonBackTextSize = 3;
			
			// aapt resource value: 5
			public const int SfRadialMenu_radialCenterButtonBorderColor = 5;
			
			// aapt resource value: 6
			public const int SfRadialMenu_radialCenterButtonBorderThickness = 6;
			
			// aapt resource value: 7
			public const int SfRadialMenu_radialCenterButtonPlacement = 7;
			
			// aapt resource value: 8
			public const int SfRadialMenu_radialCenterButtonRadius = 8;
			
			// aapt resource value: 9
			public const int SfRadialMenu_radialCenterButtonText = 9;
			
			// aapt resource value: 10
			public const int SfRadialMenu_radialCenterButtonTextColor = 10;
			
			// aapt resource value: 11
			public const int SfRadialMenu_radialCenterButtonTextSize = 11;
			
			// aapt resource value: 12
			public const int SfRadialMenu_radialEnableCenterButtonAnimation = 12;
			
			// aapt resource value: 13
			public const int SfRadialMenu_radialEnableRotation = 13;
			
			// aapt resource value: 14
			public const int SfRadialMenu_radialIsDragEnabled = 14;
			
			// aapt resource value: 15
			public const int SfRadialMenu_radialIsOpen = 15;
			
			// aapt resource value: 16
			public const int SfRadialMenu_radialLayoutType = 16;
			
			// aapt resource value: 17
			public const int SfRadialMenu_radialOuterRimColor = 17;
			
			// aapt resource value: 18
			public const int SfRadialMenu_radialOuterRimThickness = 18;
			
			// aapt resource value: 19
			public const int SfRadialMenu_radialRimActiveColor = 19;
			
			// aapt resource value: 20
			public const int SfRadialMenu_radialRimColor = 20;
			
			// aapt resource value: 21
			public const int SfRadialMenu_radialRimRadius = 21;
			
			// aapt resource value: 22
			public const int SfRadialMenu_radialSelectionColor = 22;
			
			// aapt resource value: 23
			public const int SfRadialMenu_radialSeparatorColor = 23;
			
			// aapt resource value: 24
			public const int SfRadialMenu_radialSeparatorThickness = 24;
			
			// aapt resource value: 25
			public const int SfRadialMenu_radialVisibleSegmentsCount = 25;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
